### ISSUE TITLE
Add a visible text on nodefony repo to this repo

### ISSUE THREAD

**Issue by tristanleboss** [nodefony/nodefony-v7#25]
Hello,

I think it would be a good idea to add a clearly visible link to this repository on the nodefony/nodefony repository explaining this is v5 and v6 is available here.

It's not really clear for a new user like me what's going on between both repository.

**Comment by ccamensuli** [comment]
Hi tristan ,

nodefony/nodefony-core is the core development of nodefony project , this repository have all public npm packages. the repository  nodefony/nodefony  is a starter for users usage.

nodefony-core V6 is beta (trunk next).

Unfortunately, The documentation is in progress but I'm running out of time .
Some users ask me for new specifications I manage priorities in my work at the expense of exhaustive documentation and the real visibility of project .

if you have any questions I remain at your disposal .

christophe
